### PR TITLE
Fix parsing of ISO 8601 decimal fractions of a second

### PR DESCRIPTION
**Pull request by erszcz**
It's based on top of #77 - please see the discussion there for some context. The solution here is not complete yet - any decimal fraction should be accepted, but 3 and 6 places after the comma are a good start, since milliseconds and microseconds are SI standardized submultiples of a second.

### CODE REVIEW

**Comment by tsloughter** [comment]
Great. But this only accepts 3 or 6 decimal places? Not everything under 6?

**Comment by erszcz** [comment]
Ok, I didn't realize it's not that much more effort to do full support. The caveats now:

- `2001-03-10T17:16:17.1234Z` will be parsed correctly, but when formatted won't look the same - formatting always prints the insignificant trailing zeros: `2001-03-10T17:16:17.123400Z`

- `ec_date:tokenise/2` doesn't just tokenise - it also converts the fractional part into microseconds. I hope we can live with this slight name inaccuracy.

**Comment by erszcz** [comment]
Any comments, required fixes, need for more tests? I'd be happy to see this merged, otherwise the library is missing quite a useful piece of functionality.

**Comment by tsloughter** [comment]
Sorry for the delay, i think this is good now, will merge.

**Comment by erszcz** [comment]
Thanks!

**Pull request merged**
