### PR TITLE
Update cmd_log to use cf for color encoding, including term detection

### PR DESCRIPTION
**Pull request by Licenser**
Fully use cf for coloring and term detection to deal with #80

### CODE REVIEW

**Comment by tsloughter** [comment]
@Licenser seems to be something wrong with your new version of cf published to hex.

**Comment by Licenser** [comment]
That is slightly ironic but I think it's a bug in the rebar3 it is packaged with, it builds fine with current master and other versions.

**Comment by tsloughter** [comment]
Ah ugh, need to get Travis to have the newest rebar3 already available for projects that are Erlang.

**Comment by tsloughter** [comment]
@Licenser can you have travis set the env var `DEBUG` to 1 for the run so we can see why it is failing on one of the R15s

**Comment by tsloughter** [comment]
Hehe, that only took affect for the update, need it on the other commands.

**Comment by Licenser** [comment]
seems that rebar3 calls 'list_all_dis' which doesn't exist in R15 o.O?

**Comment by tsloughter** [comment]
It does in R15B03. So just update the R15 to 03.

**Comment by tsloughter** [comment]
Argh, wtf...

**Comment by tsloughter** [comment]
Oh, haha, you must have used a rebar3 built for R16 or greater :). With a rebar3 built for R15 it'll have the proper defs defined to not use `list_dir_all`. Just replace it with the one you can download from rebar3.org, it is built with R15 I believe.

**Pull request merged**
