### PR TITLE
Allow for extra hyphens in pre-release build version

### PR DESCRIPTION
**Pull request by kubaodias**
According to https://semver.org/#spec-item-9:
`
A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-].
`

### CODE REVIEW

**Comment by kubaodias** [comment]
@ericbmerritt please make a review

**Comment by tsloughter** [comment]
Looks good, thanks

**Comment by kubaodias** [comment]
Thanks! How about creating a new build of erlware_commons and eventually merging it to rebar3?

**Comment by tsloughter** [comment]
Sure, we'll get it in with the next rebar3 release which I think needs to happen, hopefully today.

**Pull request merged**
