### PR TITLE
Bumped OTP versions

### PR DESCRIPTION
**Pull request by ariel-anieli**
* aligned OTP versions with [Debian](https://packages.debian.org/search?keywords=erlang)
* keeps versions from bullseye (old stable) to sid (unstable).

```shell
$ curl --silent https://packages.debian.org/search?keywords=erlang | \
  sed -ne '/Package erlang</,/<\/ul>/{/<\/a>/p; /br/p}' | \
  sed -e 's/<a.*$//' | \
  perl -0777 -pE 's/<li class="(\w+)">\n/$1/g; s/<br>([^\s]+)/$1/g; s/\+.*(?=\n)//g' | \
  sed -e '1i name otp-version' | \
  column -t
name          otp-version
buster        1:22.2.7
bullseye      1:23.2.6
bookworm      1:25.2.3
trixie        1:25.3.2.8
sid           1:25.3.2.8
experimental  1:26.2.1

$ curl -I  https://packages.debian.org/search?keywords=erlang
HTTP/2 200
date: Tue, 20 Feb 2024 22:21:53 GMT
server: Apache
last-modified: Tue, 20 Feb 2024 21:50:40 GMT
vary: Accept-Encoding,negotiate,accept-language
x-clacks-overhead: GNU Terry Pratchett
expires: Wed, 21 Feb 2024 09:04:02 +0000
x-content-type-options: nosniff
x-frame-options: sameorigin
referrer-policy: no-referrer
x-xss-protection: 1
permissions-policy: interest-cohort=()
strict-transport-security: max-age=15552000
age: 1873
content-length: 184625
content-type: text/html; charset=UTF-8
```

### CODE REVIEW

**Comment by ariel-anieli** [comment]
The unit tests failed in 26.2; I am checking where it comes from.

**Comment by ferd** [comment]
The failure you get on `eunit` might simply be because of changes in dialyzer defaults in newer versions. You'll want to add a rebar.config file with `{dialyzer, [{warnings, [no_unknown]}]}` in there to make it ignore calls to unknown apps or functions, or alternatively add the missing apps to the set of analyzed entries, which is a bit more work.

**Comment by ariel-anieli** [comment]
Thanks for the hints; much appreciated. R26 compiles, [`no_unknown` exists](https://www.erlang.org/doc/man/dialyzer.html#warning_options), but R25 fails: [`unknown` is the default](https://www.erlang.org/docs/25/man/dialyzer#format_warning-1).

From what I see, the easiest way is to include the missing app. Should I add `eunit` to the deps where `cf` is?

**Comment by ariel-anieli** [comment]
The PR is good to go: OTP bumped to 25.3; for 26.2, I'll look how to use `unknown` and `no_unknown` in the same `rebar.config`.

**Review by ferd — APPROVED** [review]

**Pull request merged**
